AWSTemplateFormatVersion: '2010-09-09'

Description: awsTutorial(main)
Parameters:
  ResourceNamePrefix:
    Description: Prefix of resource name
    Default: awstutorial
    Type: String
  UGCPartTemplateUrl:
    Description: Url of the cloud formation template for cognito, cloudwatch
      log  group, S3 resources.
    Type: String
    Default: https://raw.githubusercontent.com/wukakuki/awsTutorial/refs/heads/main/awsTemplate_UGC.yaml
  FriendSystemPartTemplateUrl:
    Description: Url of the cloud formation template for friend system.
    Type: String
    Default: https://raw.githubusercontent.com/wukakuki/awsTutorial/refs/heads/main/awsTemplate_FriendSystem.yaml
  DeployGameServer:
    Description: Deploy gameserver to gamelift?
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
  GameLiftPartTemplateUrl:
    Description: Url of the cloud formation template for gamelift resources.
    Type: String
    Default: https://raw.githubusercontent.com/wukakuki/awsTutorial/refs/heads/main/awsTemplate_GameLift.yaml
  GameServerBuildBucket:
    Description: S3 bucket for storing game server build files.
    Type: String
  GameServerBuildKey:
    Description: The key of the game server build file.
    Type: String
  GameServerBuildObjectVersion:
    Description: The version of the game server build file.
    Type: String
  GameServerBuildServerSdkVersion:
    Description: The server sdk version of the game server build file.
    Type: String
    Default: 5.1.3
  GameServerBuildVersion:
    Description: Version of the game server build.
    Type: String
  GameServerLaunchPath:
    Description: The launch path of the game server.
    Type: String
Conditions:
  ShouldDeployGameServer: !Equals
    - !Ref DeployGameServer
    - 'true'
Resources:
  awsTutorialUGCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref UGCPartTemplateUrl
      Outputs:
        - ExportName: awsTutorialCognitoUserPoolId
          OutputKey: awsTutorialCognitoUserPoolId
          Description: Cognito User Pool ID
        - ExportName: awsTutorialCognitoUserPoolARN
          OutputKey: awsTutorialCognitoUserPoolARN
          Description: Cognito User Pool ARN
        - ExportName: awsTutorialCognitoUserPoolClient
          OutputKey: awsTutorialCognitoUserPoolClient
          Description: Cognito User Pool Client
        - ExportName: awsTutorialIdentityPoolId
          OutputKey: awsTutorialIdentityPoolId
          Description: Cognito Identity Pool ID
        - ExportName: awsTutorialCloudWatchLogGroup
          OutputKey: awsTutorialCloudWatchLogGroup
          Description: CloudWatch Log Group
      Parameters:
        ResourceNamePrefix: !Ref ResourceNamePrefix
      Tags:
        - Key: Usage
          Value: Youtube Streamer
  awsTutorialGameLiftStack:
    Type: AWS::CloudFormation::Stack
    Condition: ShouldDeployGameServer
    Properties:
      TemplateURL: !Ref GameLiftPartTemplateUrl
      Outputs:
        - ExportName: awsTutorialAliasId
          OutputKey: awsTutorialAliasId
          Description: GameLift Alias ID
      Parameters:
        ResourceNamePrefix: !Ref ResourceNamePrefix
        BuildBucket: !Ref GameServerBuildBucket
        BuildKey: !Ref GameServerBuildKey
        BuildObjectVersion: !Ref GameServerBuildObjectVersion
        BuildServerSdkVersion: !Ref GameServerBuildServerSdkVersion
        BuildVersion: !Ref GameServerBuildVersion
        LaunchPath: !Ref GameServerLaunchPath
      Tags:
        - Key: Usage
          Value: Youtube Streamer
  awsTutorialFriendSystemStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref FriendSystemPartTemplateUrl
      Outputs:
        - ExportName: awsTutorialGraphQLHost
          OutputKey: awsTutorialGraphQLHost
          Description: GraphQL Host
        - ExportName: awsTutorialGraphQLEndpoint
          OutputKey: awsTutorialGraphQLEndpoint
          Description: GraphQL Endpoint
        - ExportName: awsTutorialGraphQLRealtimeEndpoint
          OutputKey: awsTutorialGraphQLRealtimeEndpoint
          Description: GraphQL realtime Endpoint
      Parameters:
        ResourceNamePrefix: !Ref ResourceNamePrefix
        CognitoUserPool: !ImportValue awsTutorialCognitoUserPoolId
        CognitoUserPoolArn: !ImportValue awsTutorialCognitoUserPoolARN
        CognitoUserPoolClient: !ImportValue awsTutorialCognitoUserPoolClient
      Tags:
        - Key: Usage
          Value: Youtube Streamer
Outputs:
  awsTutorialRegion:
    Description: AWS Region
    Value: !Ref AWS::Region
  awsTutorialCognitoIdentityPoolId:
    Description: Cognito Identity Pool ID
    Value: !Ref awsTutorialUGCStack.Outputs.awsTutorialCognitoIdentityPoolId
  awsTutorialCognitoUserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref awsTutorialUGCStack.Outputs.awsTutorialCognitoUserPoolId
  awsTutorialCognitoUserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref awsTutorialUGCStack.Outputs.awsTutorialCognitoUserPoolClientId
  awsTutorialAliasId:
    Description: GameLift Alias ID
    Value: !Ref awsTutorialGameLiftStack.Outputs.awsTutorialAliasId
  awsTutorialUserGeneratedContentS3Bucket:
    Description: User Generated Content S3 Bucket
    Value: !Ref awsTutorialUGCStack.Outputs.awsTutorialUserGeneratedContentS3Bucket
  awsTutorialLogGroupName:
    Description: Log Group Name
    Value: !Ref awsTutorialUGCStack.Outputs.awsTutorialLogGroupName
  awsTutorialGraphQLHost:
    Description: GraphQL Host
    Value: !GetAtt awsTutorialFriendSystemStack.Outputs.awsTutorialGraphQLHost
  awsTutorialGraphQLEndpoint:
    Description: GraphQL Endpoint
    Value: !GetAtt awsTutorialFriendSystemStack.Outputs.awsTutorialGraphQLEndpoint
  awsTutorialGraphQLRealtimeEndpoint:
    Description: GraphQL realtime Endpoint
    Value: !GetAtt awsTutorialFriendSystemStack.Outputs.awsTutorialGraphQLRealtimeEndpoint