AWSTemplateFormatVersion: '2010-09-09'

Description: awsTutorial(main)
Parameters:
  ResourceNamePrefix:
    Description: Prefix of resource name
    Default: awstutorial
    Type: String
  UGCPartTemplateUrl:
    Description: Url of the cloud formation template for cognito, cloudwatch
      log  group, S3 resources.
    Type: String
    Default: https://aws-plugin-public-resource.s3.ap-northeast-2.amazonaws.com/cloudformation+templates/awsTemplate_UGC.yaml
  FriendSystemPartTemplateUrl:
    Description: Url of the cloud formation template for friend system.
    Type: String
    Default: https://aws-plugin-public-resource.s3.ap-northeast-2.amazonaws.com/cloudformation+templates/awsTemplate_FriendSystem.yaml
  InvitationSystemPartTemplateUrl:
    Description: Url of the cloud formation template for websocket mmo.
    Type: String
    Default: https://aws-plugin-public-resource.s3.ap-northeast-2.amazonaws.com/cloudformation+templates/awsTemplate_InvitationSystem.yaml
  DeployWebSocketMMO:
    Description: Deploy WebSocketMMO?
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
  WebSocketMMOPartTemplateUrl:
    Description: Url of the cloud formation template for websocket mmo.
    Type: String
    Default: https://aws-plugin-public-resource.s3.ap-northeast-2.amazonaws.com/cloudformation+templates/awsTemplate_WebSocketMMO.yaml
  JwksUpdateInterval:
    Description: Seconds between two jwks update
    Type: Number
    Default: 3600
  PositionUpdateInterval:
    Description: Seconds between two position update. (Set to 0 to make realtime MMO system)
    Type: Number
    Default: 5
  WebSocketMMOEC2InstanceType:
    Description: ec2 instance type of the web socket mmo server
    Type: String
    Default: t4g.nano
  DeployGameServer:
    Description: Deploy gameserver to gamelift?
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
  GameLiftPartTemplateUrl:
    Description: Url of the cloud formation template for gamelift resources.
    Type: String
    Default: https://aws-plugin-public-resource.s3.ap-northeast-2.amazonaws.com/cloudformation+templates/awsTemplate_GameLift.yaml
  GameServerBuildBucket:
    Description: S3 bucket for storing game server build files.
    Type: String
    Default: awstutorial-builds-ap-northeast-2
  GameServerBuildKey:
    Description: The key of the game server build file.
    Type: String
    Default: LinuxArm64Server.zip
  GameServerBuildObjectVersion:
    Description: The version of the game server build file.
    Type: String
    Default: gkBW2iNLK.gPhqcKl69ECOjuf.3Xq3M_
  GameServerBuildServerSdkVersion:
    Description: The server sdk version of the game server build file.
    Type: String
    Default: 5.2.0
  GameServerBuildVersion:
    Description: Version of the game server build.
    Type: String
    Default: 1.0.0
  GameServerLaunchPath:
    Description: The launch path of the game server.
    Type: String
    Default: awsTutorial/Binaries/LinuxArm64/awsTutorialServer
  PrivateGamePartTemplateUrl:
    Description: Url of the cloud formation template for PrivateGame resources.
    Type: String
    Default: https://aws-plugin-public-resource.s3.ap-northeast-2.amazonaws.com/cloudformation+templates/awsTemplate_PrivateGame.yaml
  GameLiftGameSessionMaxPlayerNum:
    Description: GameLift Alias Id of the GameLift Alias which is ued to create private game session 
    Type: Number
    Default: 20
Conditions:
  ShouldDeployWebSocketMMO: !Equals
    - !Ref DeployWebSocketMMO
    - 'true'
  ShouldDeployGameServer: !Equals
    - !Ref DeployGameServer
    - 'true'
Resources:
  awsTutorialUGCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref UGCPartTemplateUrl
      Parameters:
        ResourceNamePrefix: !Ref ResourceNamePrefix
      Tags:
        - Key: Usage
          Value: Youtube Streamer
  awsTutorialGameLiftStack:
    Type: AWS::CloudFormation::Stack
    Condition: ShouldDeployGameServer
    Properties:
      TemplateURL: !Ref GameLiftPartTemplateUrl
      Parameters:
        ResourceNamePrefix: !Ref ResourceNamePrefix
        GameServerBuildBucket: !Ref GameServerBuildBucket
        GameServerBuildKey: !Ref GameServerBuildKey
        GameServerBuildObjectVersion: !Ref GameServerBuildObjectVersion
        GameServerBuildServerSdkVersion: !Ref GameServerBuildServerSdkVersion
        GameServerBuildVersion: !Ref GameServerBuildVersion
        GameServerLaunchPath: !Ref GameServerLaunchPath
      Tags:
        - Key: Usage
          Value: Youtube Streamer
  awsTutorialPrivateGameStack:
    Type: AWS::CloudFormation::Stack
    Condition: ShouldDeployGameServer
    Properties:
      TemplateURL: !Ref PrivateGamePartTemplateUrl
      Parameters:
        ResourceNamePrefix: !Ref ResourceNamePrefix
        CognitoUserPool: !GetAtt awsTutorialUGCStack.Outputs.awsTutorialCognitoUserPoolId
        CognitoUserPoolArn: !GetAtt awsTutorialUGCStack.Outputs.awsTutorialCognitoUserPoolArn
        CognitoUserPoolClient: !GetAtt awsTutorialUGCStack.Outputs.awsTutorialCognitoUserPoolClientId
        GameLiftFleetId: !GetAtt awsTutorialGameLiftStack.Outputs.awsTutorialFleetId
        GameLiftAliasId: !GetAtt awsTutorialGameLiftStack.Outputs.awsTutorialAliasId
        GameLiftGameSessionMaxPlayerNum: !Ref GameLiftGameSessionMaxPlayerNum
      Tags:
        - Key: Usage
          Value: Youtube Streamer
  awsTutorialFriendSystemStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: awsTutorialUGCStack
    Properties:
      TemplateURL: !Ref FriendSystemPartTemplateUrl
      Parameters:
        ResourceNamePrefix: !Ref ResourceNamePrefix
        CognitoUserPool: !GetAtt awsTutorialUGCStack.Outputs.awsTutorialCognitoUserPoolId
        CognitoUserPoolArn: !GetAtt awsTutorialUGCStack.Outputs.awsTutorialCognitoUserPoolArn
        CognitoUserPoolClient: !GetAtt awsTutorialUGCStack.Outputs.awsTutorialCognitoUserPoolClientId
      Tags:
        - Key: Usage
          Value: Youtube Streamer
  awsTutorialInvitationSystemStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: awsTutorialUGCStack
    Properties:
      TemplateURL: !Ref InvitationSystemPartTemplateUrl
      Parameters:
        ResourceNamePrefix: !Ref ResourceNamePrefix
        CognitoUserPool: !GetAtt awsTutorialUGCStack.Outputs.awsTutorialCognitoUserPoolId
        CognitoUserPoolArn: !GetAtt awsTutorialUGCStack.Outputs.awsTutorialCognitoUserPoolArn
        CognitoUserPoolClient: !GetAtt awsTutorialUGCStack.Outputs.awsTutorialCognitoUserPoolClientId
      Tags:
        - Key: Usage
          Value: Youtube Streamer
  awsTutorialWebSocketMMOStack:
    Type: AWS::CloudFormation::Stack
    Condition: ShouldDeployWebSocketMMO
    DependsOn: awsTutorialUGCStack
    Properties:
      TemplateURL: !Ref WebSocketMMOPartTemplateUrl
      Parameters:
        ResourceNamePrefix: !Ref ResourceNamePrefix
        CognitoUserPool: !GetAtt awsTutorialUGCStack.Outputs.awsTutorialCognitoUserPoolId
        CognitoUserPoolClient: !GetAtt awsTutorialUGCStack.Outputs.awsTutorialCognitoUserPoolClientId
        JwksUpdateInterval: !Ref JwksUpdateInterval
        PositionUpdateInterval: !Ref PositionUpdateInterval
      Tags:
        - Key: Usage
          Value: Youtube Streamer
Outputs:
  awsTutorialRegion:
    Description: AWS Region
    Value: !Ref AWS::Region
  awsTutorialCognitoIdentityPoolId:
    Description: Cognito Identity Pool ID
    Value: !GetAtt awsTutorialUGCStack.Outputs.awsTutorialCognitoIdentityPoolId
  awsTutorialCognitoUserPoolId:
    Description: Cognito User Pool ID
    Value: !GetAtt awsTutorialUGCStack.Outputs.awsTutorialCognitoUserPoolId
  awsTutorialCognitoUserPoolClient:
    Description: Link to Cognito User Pool Client
    Value: !Sub "https://${AWS::Region}.console.aws.amazon.com/cognito/v2/idp/user-pools/${awsTutorialUGCStack.Outputs.awsTutorialCognitoUserPoolId}/applications/app-clients/${awsTutorialUGCStack.Outputs.awsTutorialCognitoUserPoolClientId}/quick-setup-guide?region=${AWS::Region}"
  awsTutorialCognitoUserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !GetAtt awsTutorialUGCStack.Outputs.awsTutorialCognitoUserPoolClientId
  awsTutorialAliasId:
    Condition: ShouldDeployGameServer
    Description: GameLift Alias ID
    Value: !GetAtt awsTutorialGameLiftStack.Outputs.awsTutorialAliasId
  awsTutorialGameSessionQueueName:
    Condition: ShouldDeployGameServer
    Description: GameLift Game Session Queue Name
    Value: !GetAtt awsTutorialGameLiftStack.Outputs.awsTutorialGameSessionQueueName
  awsTutorialUserGeneratedContentS3Bucket:
    Description: User Generated Content S3 Bucket
    Value: !GetAtt awsTutorialUGCStack.Outputs.awsTutorialUserGeneratedContentS3Bucket
  awsTutorialLogGroupName:
    Description: Log Group Name
    Value: !GetAtt awsTutorialUGCStack.Outputs.awsTutorialLogGroupName
  awsTutorialFriendSystemGraphQLHost:
    Description: Friend System GraphQL Host
    Value: !GetAtt awsTutorialFriendSystemStack.Outputs.awsTutorialFriendSystemGraphQLHost
  awsTutorialFriendSystemGraphQLEndpoint:
    Description: Friend System GraphQL Endpoint
    Value: !GetAtt awsTutorialFriendSystemStack.Outputs.awsTutorialFriendSystemGraphQLEndpoint
  awsTutorialFriendSystemGraphQLRealtimeEndpoint:
    Description: Friend System GraphQL realtime Endpoint
    Value: !GetAtt awsTutorialFriendSystemStack.Outputs.awsTutorialFriendSystemGraphQLRealtimeEndpoint
  awsTutorialInvitationSystemGraphQLHost:
    Description: Invitation System GraphQL Host
    Value: !GetAtt awsTutorialInvitationSystemStack.Outputs.awsTutorialInvitationSystemGraphQLHost
  awsTutorialInvitationSystemGraphQLEndpoint:
    Description: Invitation System GraphQL Endpoint
    Value: !GetAtt awsTutorialInvitationSystemStack.Outputs.awsTutorialInvitationSystemGraphQLEndpoint
  awsTutorialInvitationSystemGraphQLRealtimeEndpoint:
    Description: Invitation System GraphQL realtime Endpoint
    Value: !GetAtt awsTutorialInvitationSystemStack.Outputs.awsTutorialInvitationSystemGraphQLRealtimeEndpoint
  awsTutorialWebSocketMMODNSName:
    Condition: ShouldDeployWebSocketMMO
    Description: The DNSName of the WebSocket MMO Server
    Value: !GetAtt awsTutorialWebSocketMMOStack.Outputs.awsTutorialWebSocketMMODNSName
  awsTutorialPrivateGameGraphQLHost:
    Condition: ShouldDeployGameServer
    Description: Private Game GraphQL Host
    Value: !GetAtt awsTutorialPrivateGameStack.Outputs.awsTutorialPrivateGameGraphQLHost
  awsTutorialPrivateGameGraphQLEndpoint:
    Condition: ShouldDeployGameServer
    Description: Private Game GraphQL Endpoint
    Value: !GetAtt awsTutorialPrivateGameStack.Outputs.awsTutorialPrivateGameGraphQLEndpoint