AWSTemplateFormatVersion: '2010-09-09'

Description: awsTutorial(main)
Parameters:
  ResourceNamePrefix:
    Description: Prefix of resource name
    Default: awstutorial
    Type: String
  UGCPartTemplateUrl:
    Description: Url of the cloud formation template for cognito, cloudwatch
      log  group, S3 resources.
    Type: String
    Default: https://aws-plugin-public-resource.s3.ap-northeast-2.amazonaws.com/cloudformation+templates/awsTemplate_UGC.yaml
  FriendSystemPartTemplateUrl:
    Description: Url of the cloud formation template for friend system.
    Type: String
    Default: https://aws-plugin-public-resource.s3.ap-northeast-2.amazonaws.com/cloudformation+templates/awsTemplate_FriendSystem.yaml
  # InvitationSystemPartTemplateUrl:
  #   Description: Url of the cloud formation template for websocket mmo.
  #   Type: String
  #   Default: https://aws-plugin-public-resource.s3.ap-northeast-2.amazonaws.com/cloudformation+templates/awsTemplate_InvitationSystem.yaml
  WebSocketMMOPartTemplateUrl:
    Description: Url of the cloud formation template for websocket mmo.
    Type: String
    Default: https://aws-plugin-public-resource.s3.ap-northeast-2.amazonaws.com/cloudformation+templates/awsTemplate_WebSocketMMO.yaml
  JwksUpdateInterval:
    Description: Seconds between two jwks update
    Type: Number
    Default: 3600
  PositionUpdateInterval:
    Description: Seconds between two position update. (Set to 0 to make realtime MMO system)
    Type: Number
    Default: 5
  WebSocketMMOEC2InstanceType:
    Description: ec2 instance type of the web socket mmo server
    Type: String
    Default: t4g.nano
  DeployGameServer:
    Description: Deploy gameserver to gamelift?
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
  GameLiftPartTemplateUrl:
    Description: Url of the cloud formation template for gamelift resources.
    Type: String
    Default: https://aws-plugin-public-resource.s3.ap-northeast-2.amazonaws.com/cloudformation+templates/awsTemplate_GameLift.yaml
  GameServerBuildBucket:
    Description: S3 bucket for storing game server build files.
    Type: String
  GameServerBuildKey:
    Description: The key of the game server build file.
    Type: String
  GameServerBuildObjectVersion:
    Description: The version of the game server build file.
    Type: String
  GameServerBuildServerSdkVersion:
    Description: The server sdk version of the game server build file.
    Type: String
    Default: 5.2.0
  GameServerBuildVersion:
    Description: Version of the game server build.
    Type: String
  GameServerLaunchPath:
    Description: The launch path of the game server.
    Type: String
    Default: awsTutorial/Binaries/LinuxArm64/awsTutorialServer
Conditions:
  ShouldDeployGameServer: !Equals
    - !Ref DeployGameServer
    - 'true'
Resources:
  awsTutorialUGCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref UGCPartTemplateUrl
      Parameters:
        ResourceNamePrefix: !Ref ResourceNamePrefix
      Tags:
        - Key: Usage
          Value: Youtube Streamer
  awsTutorialGameLiftStack:
    Type: AWS::CloudFormation::Stack
    Condition: ShouldDeployGameServer
    Properties:
      TemplateURL: !Ref GameLiftPartTemplateUrl
      Parameters:
        ResourceNamePrefix: !Ref ResourceNamePrefix
        GameServerBuildBucket: !Ref GameServerBuildBucket
        GameServerBuildKey: !Ref GameServerBuildKey
        GameServerBuildObjectVersion: !Ref GameServerBuildObjectVersion
        GameServerBuildServerSdkVersion: !Ref GameServerBuildServerSdkVersion
        GameServerBuildVersion: !Ref GameServerBuildVersion
        GameServerLaunchPath: !Ref GameServerLaunchPath
      Tags:
        - Key: Usage
          Value: Youtube Streamer
  awsTutorialFriendSystemStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: awsTutorialUGCStack
    Properties:
      TemplateURL: !Ref FriendSystemPartTemplateUrl
      Parameters:
        ResourceNamePrefix: !Ref ResourceNamePrefix
        CognitoUserPool: !GetAtt awsTutorialUGCStack.Outputs.awsTutorialCognitoUserPoolId
        CognitoUserPoolArn: !GetAtt awsTutorialUGCStack.Outputs.awsTutorialCognitoUserPoolArn
        CognitoUserPoolClient: !GetAtt awsTutorialUGCStack.Outputs.awsTutorialCognitoUserPoolClientId
      Tags:
        - Key: Usage
          Value: Youtube Streamer
  # awsTutorialInvitationSystemStack:
  #   Type: AWS::CloudFormation::Stack
  #   DependsOn: awsTutorialUGCStack
  #   Properties:
  #     TemplateURL: !Ref InvitationSystemPartTemplateUrl
  #     Parameters:
  #       ResourceNamePrefix: !Ref ResourceNamePrefix
  #       CognitoUserPool: !GetAtt awsTutorialUGCStack.Outputs.awsTutorialCognitoUserPoolId
  #       CognitoUserPoolArn: !GetAtt awsTutorialUGCStack.Outputs.awsTutorialCognitoUserPoolArn
  #       CognitoUserPoolClient: !GetAtt awsTutorialUGCStack.Outputs.awsTutorialCognitoUserPoolClientId
  #     Tags:
  #       - Key: Usage
  #         Value: Youtube Streamer
  awsTutorialWebSocketMMOStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: awsTutorialUGCStack
    Properties:
      TemplateURL: !Ref WebSocketMMOPartTemplateUrl
      Parameters:
        ResourceNamePrefix: !Ref ResourceNamePrefix
        CognitoUserPool: !GetAtt awsTutorialUGCStack.Outputs.awsTutorialCognitoUserPoolId
        CognitoUserPoolClient: !GetAtt awsTutorialUGCStack.Outputs.awsTutorialCognitoUserPoolClientId
        JwksUpdateInterval: !Ref JwksUpdateInterval
        PositionUpdateInterval: !Ref PositionUpdateInterval
      Tags:
        - Key: Usage
          Value: Youtube Streamer
Outputs:
  awsTutorialRegion:
    Description: AWS Region
    Value: !Ref AWS::Region
  awsTutorialCognitoIdentityPoolId:
    Description: Cognito Identity Pool ID
    Value: !GetAtt awsTutorialUGCStack.Outputs.awsTutorialCognitoIdentityPoolId
  awsTutorialCognitoUserPoolId:
    Description: Cognito User Pool ID
    Value: !GetAtt awsTutorialUGCStack.Outputs.awsTutorialCognitoUserPoolId
  awsTutorialCognitoUserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !GetAtt awsTutorialUGCStack.Outputs.awsTutorialCognitoUserPoolClientId
  awsTutorialAliasId:
    Condition: ShouldDeployGameServer
    Description: GameLift Alias ID
    Value: !GetAtt awsTutorialGameLiftStack.Outputs.awsTutorialAliasId
  awsTutorialUserGeneratedContentS3Bucket:
    Description: User Generated Content S3 Bucket
    Value: !GetAtt awsTutorialUGCStack.Outputs.awsTutorialUserGeneratedContentS3Bucket
  awsTutorialLogGroupName:
    Description: Log Group Name
    Value: !GetAtt awsTutorialUGCStack.Outputs.awsTutorialLogGroupName
  awsTutorialGraphQLHost:
    Description: GraphQL Host
    Value: !GetAtt awsTutorialFriendSystemStack.Outputs.awsTutorialGraphQLHost
  awsTutorialGraphQLEndpoint:
    Description: GraphQL Endpoint
    Value: !GetAtt awsTutorialFriendSystemStack.Outputs.awsTutorialGraphQLEndpoint
  awsTutorialGraphQLRealtimeEndpoint:
    Description: GraphQL realtime Endpoint
    Value: !GetAtt awsTutorialFriendSystemStack.Outputs.awsTutorialGraphQLRealtimeEndpoint
  awsTutorialWebSocketMMODNSName:
    Description: The DNSName of the WebSocket MMO Server
    Value: !GetAtt awsTutorialWebSocketMMOStack.Outputs.awsTutorialWebSocketMMODNSName